import json
import os
from collections import Counter
from datetime import datetime

import yaml

from learning import store
from utils.claude_client import generate_text
from utils.logger import get_logger

logger = get_logger(__name__, log_dir="logs/monthly")

LABELS_YAML_PATH = "config/labels.yaml"
CONTEXT_FILE = "learning/db/classifier_context.txt"
SPLIT_THRESHOLD = 200   # emails/month to trigger split proposal
MERGE_THRESHOLD = 5     # emails/month below this → merge proposal


def _load_labels_yaml() -> dict:
    with open(LABELS_YAML_PATH) as f:
        return yaml.safe_load(f)


def _save_labels_yaml(data: dict) -> None:
    with open(LABELS_YAML_PATH, "w") as f:
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True)


def _analyze_misclassifications() -> list[dict]:
    ambiguous = store.get_ambiguous_classifications(days=30)
    domain_label = Counter()
    for e in ambiguous:
        key = (e.get("sender_domain", ""), e.get("label", ""))
        domain_label[key] += 1

    return [
        {"domain": domain, "label": label, "count": count}
        for (domain, label), count in domain_label.most_common(10)
        if count >= 3
    ]


def _extract_emerging_keywords(label: str, days: int = 30) -> list[str]:
    """Find new high-frequency keywords in a label's email subjects."""
    emails = [
        e for e in store.get_classifications_for_period(days=days)
        if e.get("label") == label
    ]
    if not emails:
        return []

    # Load existing keywords for this label
    data = _load_labels_yaml()
    existing_kws = set()
    for lbl in data.get("labels", []):
        if lbl["name"] == label:
            existing_kws = set(kw.lower() for kw in lbl.get("keywords", []))
            break

    # Extract word frequency from subjects
    from collections import Counter
    import re
    word_counts: Counter = Counter()
    for e in emails:
        words = re.findall(r'\b[a-zA-Z]{4,}\b', e.get("subject", "").lower())
        word_counts.update(words)

    stopwords = {"from", "your", "this", "that", "with", "have", "been", "will",
                 "here", "they", "what", "when", "were", "which", "there"}
    new_kws = [
        word for word, count in word_counts.most_common(20)
        if word not in existing_kws and word not in stopwords and count >= 3
    ]
    return new_kws[:5]


def _propose_label_changes(label_stats: dict[str, int]) -> list[dict]:
    proposals = []
    for label, count in label_stats.items():
        if label in ("Unsubscribe Candidates",):
            continue
        if count > SPLIT_THRESHOLD:
            proposals.append({
                "action": "split",
                "label": label,
                "reason": f"{count} emails/month — consider splitting into sub-labels",
            })
        elif count < MERGE_THRESHOLD:
            proposals.append({
                "action": "merge_or_remove",
                "label": label,
                "reason": f"Only {count} emails/month — consider merging with another label",
            })
    return proposals


def _update_labels_yaml(new_keywords: dict[str, list[str]]) -> None:
    """Append newly discovered keywords to labels.yaml."""
    data = _load_labels_yaml()
    updated = []
    for lbl in data.get("labels", []):
        name = lbl["name"]
        if name in new_keywords:
            existing = lbl.get("keywords", [])
            additions = [kw for kw in new_keywords[name] if kw not in existing]
            if additions:
                lbl["keywords"] = existing + additions
                logger.info(f"Added keywords to '{name}': {additions}")
        updated.append(lbl)
    data["labels"] = updated
    _save_labels_yaml(data)


def _build_classifier_context(misclassified: list[dict]) -> str:
    """Build prior knowledge context file for future Claude classification prompts."""
    if not misclassified:
        return ""

    lines = ["# Classifier Prior Knowledge (auto-generated by monthly retrainer)\n"]
    lines.append("Known sender→label mappings based on inbox history:")
    for item in misclassified[:20]:
        lines.append(f"- Emails from {item['domain']} are likely: {item['label']}")
    return "\n".join(lines)


def run_monthly_retraining() -> dict:
    logger.info("Monthly retraining starting")

    # 1. Analyze misclassifications
    misclassified = _analyze_misclassifications()
    logger.info(f"Found {len(misclassified)} systematic misclassification patterns")

    # 2. Extract emerging keywords per label
    all_emails = store.get_classifications_for_period(days=30)
    label_counts = Counter(e.get("label", "") for e in all_emails)

    new_keywords: dict[str, list[str]] = {}
    for label in label_counts:
        kws = _extract_emerging_keywords(label)
        if kws:
            new_keywords[label] = kws

    # 3. Update labels.yaml with new keywords
    if new_keywords:
        _update_labels_yaml(new_keywords)

    # 4. Propose label changes
    proposals = _propose_label_changes(dict(label_counts))

    # 5. Update classifier context file
    context_text = _build_classifier_context(misclassified)
    if context_text:
        os.makedirs(os.path.dirname(CONTEXT_FILE), exist_ok=True)
        with open(CONTEXT_FILE, "w") as f:
            f.write(context_text)
        logger.info(f"Classifier context updated at {CONTEXT_FILE}")

    # 6. Add domain-specific rules from misclassifications to context
    domain_rules = [
        {"domain": m["domain"], "suggested_label": m["label"]}
        for m in misclassified
    ]

    result = {
        "labels_updated": list(new_keywords.keys()),
        "new_keywords_added": new_keywords,
        "label_proposals": proposals,
        "domain_rules_added": domain_rules,
        "low_confidence_patterns": misclassified,
    }

    logger.info(f"Retraining complete: {len(new_keywords)} labels updated, {len(proposals)} proposals")
    return result
